config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :quote_requests

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/quote_request.rb
class QuoteRequest < ActiveRecord::Base
  belongs_to :user
  validates_formatting_of :website, using: :url
  validates_formatting_of :callback, using: :us_phone
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/quote_requests_controller.rb
class QuoteRequestsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_quote_request, only: [:show, :edit, :update, :destroy]

  # GET /quote_requests
  # GET /quote_requests.json
  def index
    @quote_requests = QuoteRequest.all
  end

  # GET /quote_requests/1
  # GET /quote_requests/1.json
  def show
  end

  # GET /quote_requests/new
  def new
    @quote_request = QuoteRequest.new
  end

  # GET /quote_requests/1/edit
  def edit
  end

  # POST /quote_requests
  # POST /quote_requests.json
  def create
    @quote_request = QuoteRequest.new(quote_request_params)
    @quote_request.user = current_user

    respond_to do |format|
      if @quote_request.save
        format.html { redirect_to @quote_request, notice: 'Quote request was successfully created.' }
        format.json { render :show, status: :created, location: @quote_request }
      else
        format.html { render :new }
        format.json { render json: @quote_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote_requests/1
  # PATCH/PUT /quote_requests/1.json
  def update
    respond_to do |format|
      if @quote_request.update(quote_request_params)
        format.html { redirect_to @quote_request, notice: 'Quote request was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote_request }
      else
        format.html { render :edit }
        format.json { render json: @quote_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_requests/1
  # DELETE /quote_requests/1.json
  def destroy
    @quote_request.destroy
    respond_to do |format|
      format.html { redirect_to quote_requests_url, notice: 'Quote request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_request
      @quote_request = QuoteRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_request_params
      params.require(:quote_request).permit(:user_id, :website, :callback, :description, :hours, :cost, :nte)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/quote_requests_helper.rb
module QuoteRequestsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataBlender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/><!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? or Rails.env.development? %></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/quote_requests/_form.html.erb
<%= form_for @quote_request, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :website, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :website, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :callback, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :callback, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :hours, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :hours, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cost, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :cost, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nte, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nte, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  quote_requests_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/quote_requests/edit.html.erb
<%- model_class = QuoteRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => QuoteRequest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quote_requests/index.html.erb
<%- model_class = QuoteRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => QuoteRequest %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <th><%= model_class.human_attribute_name(:callback) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:hours) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:nte) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @quote_requests.each do |quote_request| %>
      <tr>
        <td><%= quote_request.id %></td>
        <td><%= quote_request.website %></td>
        <td><%= quote_request.callback %></td>
        <td><%= quote_request.description %></td>
        <td><%= quote_request.hours %></td>
        <td><%= quote_request.cost %></td>
        <td><%= quote_request.nte %></td>
        <td><%=l quote_request.created_at, format: :long %></td>
        <td>
          <%= link_to quote_request_path(quote_request), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to quote_request_path(quote_request), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_quote_request_path,
            :class => 'btn btn-primary' %>

app/views/quote_requests/new.html.erb
<%- model_class = QuoteRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => QuoteRequest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quote_requests/show.html.erb
<%- model_class = QuoteRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => QuoteRequest %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:website) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.website %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:callback) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.callback %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:hours) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.hours %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cost) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.cost %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nte) %></dt>
      <dd><pre class="prettyprint"><%= @quote_request.nte %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              quote_requests_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quote_request_path(@quote_request), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quote_request_path(@quote_request),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>